### ISSUE TITLE
Update gitignore

### ISSUE THREAD

**Issue by jaygraygray** [ngray122/iSmile#9]
Update gitignore file to include node_modules folder and .DS_Store file.

Node_modules should never be checked into a git repo. It's a huge folder whose contents are dictated by the package.json and package-lock.json files.

The DS_Store file is a mac operating system file that is unrelated to your app code

**Comment by ngray122** [comment]
I added the DS_file to the .gitignore file but I can still see it when I push.  I can't see that actual file in my VS code

**Comment by jaygraygray** [comment]
The filename is actually `.DS_Store`. There's a `.` before the name. This is what makes it a "hidden" file. GitHub hosts a bunch of gitignore templates, and if you look at any of them (https://github.com/github/gitignore/blob/main/Node.gitignore) you'll see a lot of the entries are for files that start with a `.` 

This is to hide files that are autogenerated or often don't need to be directly modified by users.

**Comment by jaygraygray** [comment]
@ngray122 changes to gitignore file look good. To get rid of the .DS_Store file you'll need to delete the file in a commit
